version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: apinew
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 5002:5002

  ui:
    image: uinew
    depends_on:
      - api
    build:
      context: ui
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  mongo_volume: