version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: billingsoftware
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api1
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 5002:5002

  ui:
    image: api2
    depends_on:
      - api
    build:
      context: UI
      dockerfile: ./dockerfile
    ports:
      - 3002:3002

volumes:
  mongo_volume: